export const ALL_EVALUATION_REQUEST = 'ALL_EVALUATION_REQUEST'
export const ALL_EVALUATION_SUCCESS = 'ALL_EVALUATION_SUCCESS'
export const ALL_EVALUATION_FAIL = 'ALL_EVALUATION_FAIL'

export const NEW_EVALUATION_REQUEST = 'NEW_EVALUATION_REQUEST'
export const NEW_EVALUATION_SUCCESS = 'NEW_EVALUATION_SUCCESS'
export const NEW_EVALUATION_RESET = 'NEW_EVALUATION_RESET'
export const NEW_EVALUATION_FAIL = 'NEW_EVALUATION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'